### ISSUE TITLE
Rewrite?

### ISSUE THREAD

**Issue by bucaran** [lukehoban/es6features#72] opened 2015-04-03 02:59 UTC
Hey! Question: Who is the target audience for this? I would think everyone learning ES6, but if you had different design goals when your wrote this up (for example language designers, ES6 comittee members, psyionic warlords, etc), please let me know as the following feedback may be out of place.

Basically, while I do find some examples useful, most sections are either too difficult to understand or the examples are just lacking. I think this guide could be partially rewritten using a simpler language for the benefit of everyone. I want to help of course!

For example, important concepts like Symbols are not given enough attention and the given explanation might as well be written in old Persian.

What would be some of the things you would like to improve about the current guide? or should I just cherry pick and send PRs your way?

**Comment by getify** [comment] 2015-04-03 03:03
possible dupe of:

https://github.com/lukehoban/es6features/pull/66#issuecomment-81215994

**Comment by bucaran** [comment] 2015-04-03 03:13
Thanks.

TBH I find most of the written explanations unnecesarily too technical, so this is hardly a sales brochure :smile: , but most of the examples speak for themselves so it's passable.

For example:

> Calls in tail-position are guaranteed to not grow the stack unboundedly. Makes recursive algorithms safe in the face of unbounded inputs.

If you can read the above and be like, `Mmm, sounds pretty nifty, I should surely take a closer look at ES6 later, but first let me finish this OCamel virtual machine with V8 bindings Sunday afternoon thing.`, then sure, this guide needs no further revision.

**Closed** 2015-04-12 00:43 UTC

**Comment by lukehoban** [comment] 2015-04-12 00:46
As @getify notes in #66, there are many other good ES6 introductory writeups targeting at various different audiences.  This one is a little on the short and technical side, but I suspect that is also part of what it's existing audience has found valuable. So for now, I don't plan to rewrite this particular text.
